### ISSUE TITLE
Error when initialising a project 

### ISSUE THREAD

**Issue by Rhys-McAlister** [ericmjl/pyds-cli#13]
On a fresh install of pyds, I'm getting the following error when trying to initialize a project.

Ubuntu running on WSL in windows 11. Python 3.11.5 using miniconda/

```❯ pyds project initialize
2023-09-14 08:30:20.388 | INFO     | pyds.utils:run:61 - + bash -c 'source activate base && which conda'
Project name [.]: test
Project description: test
License [MIT]:
Auto create env [Y/n]:
Auto jupyter kernel [Y/n]:
Auto pre commit [Y/n]:
Creating directory structure... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Creating template files... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━  93% -:--:--
Traceback (most recent call last):
  File "/home/rhysmcalister/miniconda3/bin/pyds", line 8, in <module>
    sys.exit(app())
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/pyds/cli/project.py", line 82, in initialize
    copy_templates(templates, information)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/pyds/utils/project.py", line 121, in copy_templates
    write_template(
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/pyds/utils/project.py", line 146, in write_template
    text = template.render(**information)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/pyds/cli/templates/.github/workflows/release-pypi-package.yaml.j2", line 40, in top-level template code
    bumpversion --dry-run ${{ github.event.inputs.version_name }} --allow-dirty --verbose
  File "/home/rhysmcalister/miniconda3/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'github' is undefined
```

**Comment by ericmjl** [comment]
@Rhys-McAlister thanks for pinging in! Let me dig and see whether the issue has been resolved; in dog-fooding this tool, I remember encountering the same issue before.

**Comment by ericmjl** [comment]
Ah yes, the bug should be fixed! Please install the latest version of pyds-cli:

```python
pip install -U pyds-cli
```

In one of the latest commits, I have fixed the issue by ensuring that the relevant `${{ github.variables }}` are encased within Jinja2 `{% raw %}` blocks so that they don't get templated.

**Comment by ericmjl** [comment]
If you're okay with it, I will be closing this issue as I believe it is resolved. But if not, please feel free to reopen!
